### ISSUE TITLE
CSRF mismatch after npm audit fix

### ISSUE THREAD

**Issue by fdalex** [justnixx/laravel-breeze-api-react#4]
Hi,
When I initiate the project, I run (on frontend)

npm install

Everything is ok at this point, I can login.

Now I see there are some vulnerability found, so as suggested i run npm audit fix

But then I cannot login anymore, I have a CSRF token mismatch error from the server.

Here are the vulnerability from npm audit :

```
# npm audit report

@babel/traverse  <7.23.2
Severity: critical
Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code - https://github.com/advisories/GHSA-67hx-6x53-jw92
fix available via `npm audit fix`
node_modules/@babel/traverse

axios  0.8.1 - 1.5.1
Severity: moderate
Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
fix available via `npm audit fix`
node_modules/axios

postcss  <8.4.31
Severity: moderate
PostCSS line return parsing error - https://github.com/advisories/GHSA-7fh5-64p2-3v2j
fix available via `npm audit fix`
node_modules/postcss

semver  6.0.0 - 6.3.0
Severity: moderate
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
fix available via `npm audit fix`
node_modules/@babel/core/node_modules/semver
node_modules/@babel/helper-compilation-targets/node_modules/semver

word-wrap  <1.2.4
Severity: moderate
word-wrap vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-j8xg-fqg3-53r7
fix available via `npm audit fix`
node_modules/word-wrap

5 vulnerabilities (4 moderate, 1 critical)

To address all issues, run:
  npm audit fix
```

Any idea why I get CSRF token mismatch after running npm audit fix ?

**Comment by ccnixx** [comment]
Hi @fdalex ,

Thank you for bringing this to my attention. I appreciate your effort in trying to resolve the vulnerabilities by running `npm audit fix`. I understand that you're currently facing a CSRF token mismatch error after this operation.

I'm currently occupied with other tasks but will aim to investigate and reproduce the issue as soon as possible. In the meantime, here are a few suggestions that you might want to try:

1. **Revert Changes:** If possible, consider reverting the changes made by `npm audit fix` and check if the CSRF token mismatch issue persists. This will help isolate whether the problem is related to the specific package updates.

   ```bash
   npm audit fix --force --production
   ```

2. **Manual Updates:** Instead of relying solely on `npm audit fix`, you can manually update the vulnerable packages to the fixed versions mentioned in the audit report. Modify your `package.json` or run individual `npm install` commands for each package.

   Example:
   ```bash
   npm install @babel/traverse@latest axios@latest postcss@latest semver@latest word-wrap@latest
   ```

3. **Check Compatibility:** Ensure that the updated versions of the packages are compatible with your project's dependencies. Sometimes, conflicts may arise when updating certain packages.

Once I have the opportunity to investigate further, I will provide more insights into the CSRF token mismatch issue and suggest a resolution. Your patience is appreciated, and I'll get back to you as soon as I have more information.

**Comment by fdalex** [comment]
Hi @justnixx ,
looks like the problem comes from axios version > 1.5.1. Didn't find a solution yet but I've seen many posts talking about CSRF and axios last version.

**Comment by ccnixx** [comment]
@fdalex I will work on resolving the issue as soon as possible and will keep you updated. 
Thank you for your patience.
